'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace KVHost
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType", [Namespace]:="http://schemas.datacontract.org/2004/07/WCF_KVHOSTLINK"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CompositeType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BoolValueField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StringValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BoolValue() As Boolean
            Get
                Return Me.BoolValueField
            End Get
            Set
                If (Me.BoolValueField.Equals(value) <> true) Then
                    Me.BoolValueField = value
                    Me.RaisePropertyChanged("BoolValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StringValue() As String
            Get
                Return Me.StringValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StringValueField, value) <> true) Then
                    Me.StringValueField = value
                    Me.RaisePropertyChanged("StringValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="KVHost.IKVHOSTService1")>  _
    Public Interface IKVHOSTService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IKVHOSTService1/GetData", ReplyAction:="http://tempuri.org/IKVHOSTService1/GetDataResponse")>  _
        Function GetData(ByVal IP As String, ByVal Port As String, ByVal Command As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IKVHOSTService1/GetData", ReplyAction:="http://tempuri.org/IKVHOSTService1/GetDataResponse")>  _
        Function GetDataAsync(ByVal IP As String, ByVal Port As String, ByVal Command As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IKVHOSTService1/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IKVHOSTService1/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContract(ByVal composite As KVHost.CompositeType) As KVHost.CompositeType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IKVHOSTService1/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IKVHOSTService1/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContractAsync(ByVal composite As KVHost.CompositeType) As System.Threading.Tasks.Task(Of KVHost.CompositeType)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IKVHOSTService1Channel
        Inherits KVHost.IKVHOSTService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class KVHOSTService1Client
        Inherits System.ServiceModel.ClientBase(Of KVHost.IKVHOSTService1)
        Implements KVHost.IKVHOSTService1
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetData(ByVal IP As String, ByVal Port As String, ByVal Command As String) As String Implements KVHost.IKVHOSTService1.GetData
            Return MyBase.Channel.GetData(IP, Port, Command)
        End Function
        
        Public Function GetDataAsync(ByVal IP As String, ByVal Port As String, ByVal Command As String) As System.Threading.Tasks.Task(Of String) Implements KVHost.IKVHOSTService1.GetDataAsync
            Return MyBase.Channel.GetDataAsync(IP, Port, Command)
        End Function
        
        Public Function GetDataUsingDataContract(ByVal composite As KVHost.CompositeType) As KVHost.CompositeType Implements KVHost.IKVHOSTService1.GetDataUsingDataContract
            Return MyBase.Channel.GetDataUsingDataContract(composite)
        End Function
        
        Public Function GetDataUsingDataContractAsync(ByVal composite As KVHost.CompositeType) As System.Threading.Tasks.Task(Of KVHost.CompositeType) Implements KVHost.IKVHOSTService1.GetDataUsingDataContractAsync
            Return MyBase.Channel.GetDataUsingDataContractAsync(composite)
        End Function
    End Class
End Namespace
